[display]
fps = 20.0

#[display.driver]
#winit_pixels = { width = 192, height = 128 }

[display.driver.rgb_led_matrix]
panel_columns = 64
panel_rows = 64
daisy_chains = 2
parallel_chains = 2
pixel_mapper_config = "Rotate:-90"

pwm_bits = 7
pwm_lsb_nanoseconds = 325

gpio_slowdown = 5

[server]
ip = "0.0.0.0"
port = 8081

[timing]
idle_seconds = 1.0
